apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: build-gcs-zip-
spec:
  taskSpec:
    inputs:
      resources:
      - name: source
        type: storage
    steps:
    - image: ubuntu
      command: ['cat', 'source/file.txt']  # tests build-gcs resource
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: storage
        params:
          - name: location
            value: gs://build-crd-tests/archive.zip
          - name: artifactType
            value: ZipArchive
          - name: type
            value: build-gcs
