kind: Secret
apiVersion: v1
metadata:
  name: secret-env-password
stringData:
  ninja: SECRET_PASSWORD
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: secret-env
spec:
  taskSpec:
    steps:
    - name: secret
      image: ubuntu
      command: ['bash']
      args:
      - '-c'
      - '[[ $SECRET_PASSWORD == SECRET_PASSWORD ]]'
      env:
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-env-password
            key: ninja
