apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: steps-run-in-order-
spec:
  taskSpec:
    steps:
    - image: busybox
      command: ['/bin/sh']
      args: ['-c', 'sleep 3 && touch foo']
    - image: busybox
      command: ['/bin/sh']
      args: ['-c', 'ls', 'foo']
