apiVersion: v1
kind: ConfigMap
metadata:
  name: config-for-testing-volume-args
data:
  test.data: tasks are my jam
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: configmap-volume
spec:
  taskSpec:
    inputs:
      params:
      - name: CFGNAME
        description: Name of config map
        type: string
    steps:
    - name: read
      image: ubuntu
      command: ["/bin/bash"]
      args: ["-c", "cat /configmap/test.data"]
      volumeMounts:
      - name: custom
        mountPath: /configmap
    volumes:
    - name: custom
      configMap:
        name: "$(inputs.params.CFGNAME)"
  inputs:
    params:
    - name: CFGNAME
      value: config-for-testing-volume-args
